### 회원가입 API
// POST http://localhost:8081/user/register
POST http://3.34.149.107:8081/user/register
Content-Type: application/json

{
  "userId": "testID3",
  "password": "testPW3",
  "nickname": "testnickname3",
  "email" : "test2@test.com",
  "phone": "010-3333-3333"
}

### 로그인 API
POST http://3.34.149.107:8081/user/login
// POST http://localhost:8081/user/login
Content-Type: application/json

{
"userId": "testID6",
"password": "testPW6"
}